export const productsLocators = {
  categoryPills: 'button:has-text("All"), button:has-text("Toothbrush"), button:has-text("Home Cleaning")',
  allCategoryButtons: 'div.flex.gap-2.overflow-x-auto button, div.flex.flex-wrap button',
  showingProductsCountText: 'text=/Showing \\d+ of \\d+ products/i',
  productCard: 'div.bg-white.rounded-2xl.shadow',
  productTitle: 'h3',
  productCategory: 'p.text-\\[11px\\]',
  productPrice: 'span.font-bold',
  blurredPrice: 'span.blur-sm',
  requestAccessButton: 'button:has-text("Request Access")',
  addButton: 'button:has-text("Add")',
  incrementButton: 'button:has-text("+")',
  decrementButton: 'button:has-text("−")',
  quantityText: 'span.min-w-\\[1\\.5rem\\]',
  outOfStockBadge: 'div:has-text("Out of Stock")',
  noProductsFound: 'text=No products found',
};
